### ISSUE TITLE
TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by markburns** [azu/get-github-pr-review-comments#6]
Thanks for the awesome library. It really improves my workflow when combined with iTerm Command click to open straight in my text editor.

Also sorry for the minimal bug report, but I get this error occasionally. (Not sure of the cause)
I have a script I name `comments` which has the following hacky bash in it to grab the current repo name and SHA.

```
get-github-pr-review-comments --repo '`cat .git/config | grep -o "[^\ ]*\.git" | grep -o ":.*\." | sed -e 's/://'  | sed -e "s/\.//"`' --projectRoot .  `git rev-parse HEAD`
```

I.e. something like:
```
get-github-pr-review-comments --repo 'azu/get-github-pr-review-comments' --projectRoot . e452b8ab4a09ab42d5dee1ba96cb34bc2f676822
```

### Error output
```
Cannot read property 'data' of undefined TypeError: Cannot read property 'data' of undefined
    at defaultFormatter (/usr/local/lib/node_modules/get-github-pr-review-comments/lib/formatter.js:54:31)
    at /usr/local/lib/node_modules/get-github-pr-review-comments/lib/cli.js:59:16
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

It doesn't always happen though, so not sure of the cause. Apologies I haven't had a chance to debug the issue.

**Comment by markburns** [comment]
Just realised what this is. If you have local commits that are not on the GitHub branch then you get this exception.

**Comment by azu** [comment]
I will be fixed in https://github.com/azu/get-github-pr-review-comments/releases/tag/1.2.2.
